apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-platform-api
    newName: jhjun07/jifelog-platform-api
    newTag: dev-ab5cc0d3f6b27f0cc00a233c20c7e9bb6bf8aa8a

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
