apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-platform-api
    newName: jhjun07/jifelog-platform-api
    newTag: dev-c4607c3869e0052e1187941336825814726552c3

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
