apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-platform-api
    newName: jhjun07/jifelog-platform-api
    newTag: dev-dd9b35f4af5c0ea24c9bde645eb053ad189270a5

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
